#!/usr/bin/env bash
# mpg123/mayhem/build.sh — build the two mpg123 MP3-decoder libFuzzer harnesses (read_fuzzer,
# decode_fuzzer) plus their standalone (non-fuzzer) reproducers, AND a small golden decode test
# binary for mayhem/test.sh.
#
# mpg123 is the real-time MPEG audio (MP1/2/3) decoder library (libmpg123). The OSS-Fuzz integration
# builds libmpg123 via autotools (`./configure --enable-static; make; make install`) and links each
# harness against the static libmpg123.a. We do the SAME here, but compile the library WITH
# $SANITIZER_FLAGS so the FUZZED decoder code is instrumented (CFLAGS flow into configure/make), then
# each harness is linked twice: once with the libFuzzer engine, once with the standalone driver.
#
# Harnesses (the OSS-Fuzz harnesses verbatim, copied into mayhem/ and committed):
#   read_fuzzer.c   — file-input: writes the input bytes to a temp file, then drives the full
#       blocking decode path mpg123_open()->mpg123_read() loop (bounded by frame/stream caps).
#   decode_fuzzer.cc — C++/FuzzedDataProvider: feeds the input in chunks through the streaming-feed
#       path mpg123_open_feed()->mpg123_decode(). (Needs $CXX + fuzzer/FuzzedDataProvider.h.)
set -euo pipefail

# clang rejects SOURCE_DATE_EPOCH='' (empty) — must be unset or a valid integer.
[ -n "${SOURCE_DATE_EPOCH:-}" ] || unset SOURCE_DATE_EPOCH

# Build knobs from the base ENV, overridable. SANITIZER_FLAGS uses `=` (not `:=`) so an explicit
# empty value (--build-arg SANITIZER_FLAGS=) is honored → no-sanitizer build (natural crash).
: "${SANITIZER_FLAGS=-fsanitize=address,undefined -fno-sanitize-recover=all -fno-omit-frame-pointer}"
: "${DEBUG_FLAGS:=-g -gdwarf-3}"
export DEBUG_FLAGS
: "${CC:=clang}" ; : "${CXX:=clang++}" ; : "${LIB_FUZZING_ENGINE:=-fsanitize=fuzzer}"

# Narrow, documented UBSan relax — keep ASan + ALL other UBSan checks ON and halting.
# mpg123 1.10.0 resets its decode buffers with `memset(fr->rawbuffs, 0, fr->rawbuffss)`
# (src/libmpg123/frame.c:207) where, before the raw buffers are allocated, rawbuffs is NULL and
# rawbuffss is 0 — a zero-length memset on a NULL pointer. libc declares memset's dest
# __attribute__((nonnull)), so halting UBSan's `nonnull-attribute` check aborts on this benign
# zero-length op for ESSENTIALLY EVERY input (it fires during handle/format reset), before the
# fuzzer can explore. Relax ONLY that one check; real null-deref bugs are still caught by ASan and
# by UBSan's `null` check (both still on). Smoke-tested: a valid MP3 then decodes to completion.
SANITIZER_FLAGS="$SANITIZER_FLAGS -fno-sanitize=nonnull-attribute"
# Coverage for the FUZZED library: SANITIZER_FLAGS (ASan+UBSan) carries NO SanitizerCoverage, so a
# lib built with only those flags gives libFuzzer ZERO edge feedback (read_fuzzer was stuck at cov 8
# = its harness TU alone; the decoder was invisible). Harness TUs get coverage from -fsanitize=fuzzer,
# but the library .a needs fuzzer-no-link (SanCov, no libFuzzer main) added to its compile. Standalone
# reproducers link this same lib; ASan supplies weak SanCov callbacks. The golden binary uses a
# separate clean lib and is unaffected.
: "${COV_FLAGS:=-fsanitize=fuzzer-no-link}"
: "${MAYHEM_JOBS:=$(nproc)}"
export SANITIZER_FLAGS CC CXX LIB_FUZZING_ENGINE MAYHEM_JOBS

cd "$SRC"

# ── 1) Build libmpg123 (instrumented with $SANITIZER_FLAGS) via the project's own autotools ──────
# mpg123.h is generated by configure from src/libmpg123/mpg123.h.in (it resolves the
# @LARGEFILE_SUFFIX@ symbol-alias macros), so we MUST run the real autotools build, not compile the
# .c files loose. The sanitizer flags ride in through CFLAGS so the decoder TUs are instrumented;
# -fno-sanitize-recover etc. are compile+link flags so LDFLAGS carries them too for the final links.
PREFIX="$(mktemp -d)/inst"
echo "build.sh: configuring + building libmpg123 (static, instrumented) into $PREFIX"
# A fresh out-of-tree build keeps the committed source tree clean and avoids stale config.h.
# --disable-messages compiles libmpg123 error()/warning() (raw fprintf(stderr,...) macros in
# src/libmpg123/debug.h, gated by NO_ERROR/NO_WARNING) down to no-ops. They are NOT silenced by
# MPG123_QUIET. On a malformed free-format header the decoder resyncs byte-by-byte, calling
# error("encountered free format header...") once PER byte; with coverage now reaching that path
# the flood of stderr writes (millions of lines) stalls a single input for many minutes and makes
# fuzz-smoke / Mayhem appear to hang (it is bounded by the 1<<20 stream cap, just drowning in I/O).
# Disabling messages keeps the resync fast and silent; real crashes still surface via ASan/UBSan.
# shellcheck disable=SC2086
CC="$CC" CFLAGS="$SANITIZER_FLAGS $COV_FLAGS $DEBUG_FLAGS -O1" LDFLAGS="$SANITIZER_FLAGS $DEBUG_FLAGS" \
  ./configure --prefix="$PREFIX" --enable-static --disable-shared --disable-messages >/tmp/mpg123-configure.log 2>&1 \
  || { echo "build.sh: configure failed"; tail -40 /tmp/mpg123-configure.log; exit 1; }
make -j"$MAYHEM_JOBS" >/tmp/mpg123-make.log 2>&1 \
  || { echo "build.sh: make failed"; tail -60 /tmp/mpg123-make.log; exit 1; }
make install >/tmp/mpg123-install.log 2>&1 \
  || { echo "build.sh: make install failed"; tail -30 /tmp/mpg123-install.log; exit 1; }
# Clean the in-tree autotools artifacts so the committed checkout stays pristine for a re-build.
make distclean >/dev/null 2>&1 || true

MPG_LIB="$PREFIX/lib/libmpg123.a"
INC="-I$PREFIX/include"
[ -f "$MPG_LIB" ] || { echo "build.sh: libmpg123.a not produced"; exit 1; }
echo "build.sh: built $MPG_LIB"

OBJDIR="$(mktemp -d)"
# Standalone (non-fuzzer) run-once driver. The C harness links the C-compiled object; the C++
# harness needs the driver compiled by $CXX (as a C source) so the C++ runtime/symbols resolve.
$CC  $SANITIZER_FLAGS $DEBUG_FLAGS -c "$STANDALONE_FUZZ_MAIN" -o "$OBJDIR/standalone_c.o"
$CXX $SANITIZER_FLAGS $DEBUG_FLAGS -x c -c "$STANDALONE_FUZZ_MAIN" -o "$OBJDIR/standalone_cc.o"

# ── 2) Build each harness: libFuzzer target -> /mayhem/<name>, standalone -> /mayhem/<name>-standalone
# -lm: libmpg123's synth/layer math pulls libm.
echo "build.sh: building read_fuzzer (C)"
# shellcheck disable=SC2086
$CC  $SANITIZER_FLAGS $DEBUG_FLAGS $INC "$SRC/mayhem/read_fuzzer.c" "$MPG_LIB" $LIB_FUZZING_ENGINE -lm -o /mayhem/read_fuzzer
# shellcheck disable=SC2086
$CC  $SANITIZER_FLAGS $DEBUG_FLAGS $INC "$SRC/mayhem/read_fuzzer.c" "$MPG_LIB" "$OBJDIR/standalone_c.o" -lm -o /mayhem/read_fuzzer-standalone
echo "build.sh: built /mayhem/read_fuzzer (+ -standalone)"

echo "build.sh: building decode_fuzzer (C++)"
# shellcheck disable=SC2086
$CXX $SANITIZER_FLAGS $DEBUG_FLAGS $INC "$SRC/mayhem/decode_fuzzer.cc" "$MPG_LIB" $LIB_FUZZING_ENGINE -lm -o /mayhem/decode_fuzzer
# shellcheck disable=SC2086
$CXX $SANITIZER_FLAGS $DEBUG_FLAGS $INC "$SRC/mayhem/decode_fuzzer.cc" "$MPG_LIB" "$OBJDIR/standalone_cc.o" -lm -o /mayhem/decode_fuzzer-standalone
echo "build.sh: built /mayhem/decode_fuzzer (+ -standalone)"

# ── 3) Golden decode test binary (NORMAL flags — no sanitizers) for mayhem/test.sh ───────────────
# Honest PATCH oracle: decode a known real MP3 (mayhem/golden.mp3) through the SAME public libmpg123
# API the read fuzzer uses and assert the decoder reports the expected header-derived format. Built
# here with the project's normal flags (sanitizer-free) so test.sh only RUNS it. See golden_decode.c.
# Rebuild a clean, NON-instrumented libmpg123 for the golden binary.
GPREFIX="$(mktemp -d)/inst"
echo "build.sh: building golden decode test (normal flags)"
CC="$CC" CFLAGS="-O2" ./configure --prefix="$GPREFIX" --enable-static --disable-shared >/tmp/mpg123-gconfigure.log 2>&1 \
  || { echo "build.sh: golden configure failed"; tail -30 /tmp/mpg123-gconfigure.log; exit 1; }
make -j"$MAYHEM_JOBS" >/tmp/mpg123-gmake.log 2>&1 || { echo "build.sh: golden make failed"; tail -40 /tmp/mpg123-gmake.log; exit 1; }
make install >/dev/null 2>&1
make distclean >/dev/null 2>&1 || true
# shellcheck disable=SC2086
$CC -O2 -I"$GPREFIX/include" "$SRC/mayhem/golden_decode.c" "$GPREFIX/lib/libmpg123.a" -lm -o /mayhem/golden_decode
echo "build.sh: built /mayhem/golden_decode"

rm -rf "$OBJDIR"
ls -l /mayhem/read_fuzzer /mayhem/decode_fuzzer /mayhem/golden_decode
